name: Build and Export iOS App (IPA)

on:
  workflow_dispatch:  # Questo ci permette di avviarlo manualmente dal sito di GitHub

jobs:
  build_ios:
    runs-on: macos-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Flet
        run: |
          python -m pip install --upgrade pip
          pip install flet==0.25.2 requests  # Mettiamo le stesse librerie che hai in requirements.txt

      - name: Build IPA tramite Flet
        run: |
          # Flet applicherà in automatico la mancanza di firma se non forniamo certificati
          flet build ipa
          
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: RegistroElettronico-iOS
          path: build/**/*.ipa
          retention-days: 5
